version: "3.9"
name: tw
services:
  util:
    build:
      context: .
      dockerfile: "Dockerfile.compose"
    working_dir: /app
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
      - pnpm_store:/pnpm
  erp-db:
    image: "postgres:16"
    restart: always
    env_file:
      - "tw/erp/db-jobs/.env.docker-compose"
    volumes:
      - "erp-db:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
  erp-punch-api:
    build:
      context: .
      dockerfile: "Dockerfile.compose"
    command: "pnpm nx run tw-erp-punch-api:serve:development"
    ports:
      - "4201:4201"
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
      - pnpm_store:/pnpm/store
    env_file:
      - "tw/erp/punch-api/.env.docker-compose"
    depends_on:
      - erp-db
      - erp-db-jobs
  erp-db-jobs:
    build:
      context: .
      dockerfile: "Dockerfile.compose"
    command: "pnpm nx db-push tw-erp-db-jobs"
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
      - pnpm_store:/pnpm/store
    env_file:
      - "tw/erp/db-jobs/.env.docker-compose"
    depends_on:
      - erp-db

volumes:
  erp-db:
  node_modules:
  pnpm_store:
